// Generated by build.py -- do not edit.
const REPORT = {
 "generated": "2026-08-15",
 "windowStart": "2025-07-15",
 "windowEnd": "2026-07-16",
 "lookback": 252,
 "skip": 21,
 "displayCount": 10,
 "universe": [
  {
   "symbol": "NVDA",
   "name": "NVIDIA Corporation",
   "marketCap": 5453600360000,
   "score": 0.5490956493003553,
   "annReturn": 0.19603130800506507,
   "annVol": 0.3570075782877602
  },
  {
   "symbol": "AAPL",
   "name": "Apple Inc.",
   "marketCap": 4493302821080,
   "score": 1.931229067704273,
   "annReturn": 0.4700336624324091,
   "annVol": 0.24338576417097763
  },
  {
   "symbol": "GOOGL",
   "name": "Alphabet Inc.",
   "marketCap": 4186120293827,
   "score": 2.229870230352944,
   "annReturn": 0.6694500498312304,
   "annVol": 0.3002192866287424
  },
  {
   "symbol": "MSFT",
   "name": "Microsoft Corporation",
   "marketCap": 3678617470000,
   "score": -0.8138501303037003,
   "annReturn": -0.22403071687860565,
   "annVol": 0.2752726927683912
  },
  {
   "symbol": "AMZN",
   "name": "Amazon.com, Inc.",
   "marketCap": 2825352315000,
   "score": 0.3177741038646109,
   "annReturn": 0.0989383471518753,
   "annVol": 0.31134804865669113
  },
  {
   "symbol": "TSM",
   "name": "Taiwan Semiconductor Manufacturing Company Limited",
   "marketCap": 2211255748000,
   "score": 1.4186196978257883,
   "annReturn": 0.5585364175242894,
   "annVol": 0.39371821664419027
  },
  {
   "symbol": "AVGO",
   "name": "Broadcom Inc.",
   "marketCap": 1869681364200,
   "score": 0.6233986139731421,
   "annReturn": 0.29464084384995637,
   "annVol": 0.47263634734781496
  },
  {
   "symbol": "SPCX",
   "name": "Space Exploration Technologies Corp.",
   "marketCap": 1830621161880,
   "score": null,
   "annReturn": null,
   "annVol": null
  },
  {
   "symbol": "META",
   "name": "Meta Platforms, Inc.",
   "marketCap": 1502634953315,
   "score": -0.16467773586854706,
   "annReturn": -0.06344788688546352,
   "annVol": 0.3852851543702932
  },
  {
   "symbol": "TSLA",
   "name": "Tesla, Inc.",
   "marketCap": 1351811586544,
   "score": 0.5143174010856318,
   "annReturn": 0.22977573453953967,
   "annVol": 0.44675862425522506
  },
  {
   "symbol": "SKHY",
   "name": "SK hynix Inc.",
   "marketCap": 1180701640200,
   "score": null,
   "annReturn": null,
   "annVol": null
  },
  {
   "symbol": "LLY",
   "name": "Eli Lilly and Company",
   "marketCap": 1111405058560,
   "score": 1.0903550067732932,
   "annReturn": 0.42245661536086165,
   "annVol": 0.3874486866539413
  },
  {
   "symbol": "MU",
   "name": "Micron Technology, Inc.",
   "marketCap": 1097383087400,
   "score": 2.590537383343868,
   "annReturn": 1.9621691328028525,
   "annVol": 0.7574371037526133
  },
  {
   "symbol": "BRK-B",
   "name": "Berkshire Hathaway Inc.",
   "marketCap": 1087118917488,
   "score": 0.3276350285206779,
   "annReturn": 0.04774329992851744,
   "annVol": 0.14572098760039706
  },
  {
   "symbol": "JPM",
   "name": "JPMorgan Chase & Co.",
   "marketCap": 972233408400,
   "score": 0.8978753267276977,
   "annReturn": 0.19917263570288155,
   "annVol": 0.22182660529136633
  },
  {
   "symbol": "WMT",
   "name": "Walmart Inc.",
   "marketCap": 917327881600,
   "score": 0.7999590671298044,
   "annReturn": 0.19483977515135714,
   "annVol": 0.24356218106312397
  },
  {
   "symbol": "AMD",
   "name": "Advanced Micro Devices, Inc.",
   "marketCap": 838764334000,
   "score": 1.725667994317261,
   "annReturn": 1.1691334564025457,
   "annVol": 0.6774961697456172
  },
  {
   "symbol": "ASML",
   "name": "ASML Holding N.V.",
   "marketCap": 710741608843,
   "score": 1.7121489946002453,
   "annReturn": 0.7819800186767758,
   "annVol": 0.45672428108942326
  },
  {
   "symbol": "V",
   "name": "Visa Inc.",
   "marketCap": 679885241886,
   "score": 0.2705089891618934,
   "annReturn": 0.05876400953930924,
   "annVol": 0.21723496036629056
  },
  {
   "symbol": "XOM",
   "name": "Exxon Mobil Corporation",
   "marketCap": 663486601400,
   "score": 1.1508767043662051,
   "annReturn": 0.28807040866444433,
   "annVol": 0.25030518696882176
  },
  {
   "symbol": "JNJ",
   "name": "Johnson & Johnson",
   "marketCap": 627417052606,
   "score": 2.659198172482519,
   "annReturn": 0.501481622037884,
   "annVol": 0.188583772066044
  },
  {
   "symbol": "INTC",
   "name": "Intel Corp.",
   "marketCap": 517009974068,
   "score": 1.90884158850625,
   "annReturn": 1.442494879830667,
   "annVol": 0.7556912467312078
  },
  {
   "symbol": "MA",
   "name": "Mastercard Incorporated",
   "marketCap": 499287824440,
   "score": 0.03826446756431454,
   "annReturn": 0.008356974962718986,
   "annVol": 0.2184003984551115
  },
  {
   "symbol": "BAC",
   "name": "Bank of America Corporation",
   "marketCap": 457659089100,
   "score": 1.421376610624509,
   "annReturn": 0.30844141029886496,
   "annVol": 0.21700188957193078
  },
  {
   "symbol": "ABBV",
   "name": "AbbVie Inc.",
   "marketCap": 440726469198,
   "score": 1.3146377187895775,
   "annReturn": 0.3415323858233555,
   "annVol": 0.2597920179392188
  },
  {
   "symbol": "CSCO",
   "name": "Cisco Systems, Inc.",
   "marketCap": 440179423387,
   "score": 1.5687098626582052,
   "annReturn": 0.5106128675078747,
   "annVol": 0.3254986021714893
  },
  {
   "symbol": "ORCL",
   "name": "Oracle Corporation",
   "marketCap": 432992250400,
   "score": -1.00138419788613,
   "annReturn": -0.6260559582202618,
   "annVol": 0.6251905707537961
  },
  {
   "symbol": "COST",
   "name": "Costco Wholesale Corporation",
   "marketCap": 426227666900,
   "score": -0.08843962146947833,
   "annReturn": -0.017503504917075162,
   "annVol": 0.19791474258079964
  },
  {
   "symbol": "LRCX",
   "name": "Lam Research Corporation",
   "marketCap": 415639445200,
   "score": 1.9633082212393056,
   "annReturn": 1.1610592797369235,
   "annVol": 0.5913790138381961
  },
  {
   "symbol": "AMAT",
   "name": "Applied Materials, Inc.",
   "marketCap": 402680125620,
   "score": 1.866291716066553,
   "annReturn": 1.0421374973406141,
   "annVol": 0.5584001088195641
  },
  {
   "symbol": "PLTR",
   "name": "Palantir Technologies Inc.",
   "marketCap": 399608022800,
   "score": -0.19337342083265874,
   "annReturn": -0.10000553086675684,
   "annVol": 0.5171627539924399
  },
  {
   "symbol": "CVX",
   "name": "Chevron Corporation",
   "marketCap": 398339916000,
   "score": 1.058522032643392,
   "annReturn": 0.2399267017917432,
   "annVol": 0.2266619818886403
  },
  {
   "symbol": "CAT",
   "name": "Caterpillar Inc.",
   "marketCap": 394567835090,
   "score": 2.0779251662166485,
   "annReturn": 0.7845133464974378,
   "annVol": 0.3775464868765361
  },
  {
   "symbol": "GE",
   "name": "GE Aerospace",
   "marketCap": 382217278539,
   "score": 0.852181220189326,
   "annReturn": 0.27225012512285274,
   "annVol": 0.31947444824279037
  },
  {
   "symbol": "KO",
   "name": "The Coca-Cola Company",
   "marketCap": 377376567001,
   "score": 1.3145637985266492,
   "annReturn": 0.2301748072015518,
   "annVol": 0.17509595765494956
  },
  {
   "symbol": "UNH",
   "name": "UnitedHealth Group Incorporated",
   "marketCap": 364828851419,
   "score": 0.9887446905460717,
   "annReturn": 0.39890863381512154,
   "annVol": 0.4034495837290506
  },
  {
   "symbol": "HSBC",
   "name": "HSBC Holdings plc",
   "marketCap": 356697168800,
   "score": 1.9757285510030749,
   "annReturn": 0.5339825309099345,
   "annVol": 0.2702712023060214
  },
  {
   "symbol": "PG",
   "name": "The Procter & Gamble Company",
   "marketCap": 343625551843,
   "score": 0.10460067213996058,
   "annReturn": 0.0205583323730164,
   "annVol": 0.196541111566744
  },
  {
   "symbol": "MS",
   "name": "Morgan Stanley",
   "marketCap": 342821808000,
   "score": 1.6876646061085132,
   "annReturn": 0.4571292697840172,
   "annVol": 0.2708649977782522
  },
  {
   "symbol": "HD",
   "name": "The Home Depot, Inc.",
   "marketCap": 337883066620,
   "score": -0.015397495421929386,
   "annReturn": -0.003814335611029388,
   "annVol": 0.24772441923229566
  },
  {
   "symbol": "MRK",
   "name": "Merck & Co., Inc.",
   "marketCap": 335500348800,
   "score": 1.7263776675686546,
   "annReturn": 0.4812077427002186,
   "annVol": 0.2787383964355424
  },
  {
   "symbol": "DELL",
   "name": "Dell Technologies Inc.",
   "marketCap": 326233565636,
   "score": 1.7590325090436107,
   "annReturn": 1.1510471487687748,
   "annVol": 0.6543637726141863
  },
  {
   "symbol": "NFLX",
   "name": "Netflix, Inc.",
   "marketCap": 325453550322,
   "score": -1.5339253891211213,
   "annReturn": -0.5277363009432361,
   "annVol": 0.34404300540693716
  },
  {
   "symbol": "PANW",
   "name": "Palo Alto Networks, Inc.",
   "marketCap": 313180050000,
   "score": 1.4797957368628507,
   "annReturn": 0.610472055761452,
   "annVol": 0.4125380554586848
  },
  {
   "symbol": "GS",
   "name": "The Goldman Sachs Group, Inc.",
   "marketCap": 306636175940,
   "score": 1.5296661414639026,
   "annReturn": 0.46421100726783554,
   "annVol": 0.30347210720345946
  },
  {
   "symbol": "RY",
   "name": "Royal Bank of Canada",
   "marketCap": 300970756800,
   "score": 3.494617437311105,
   "annReturn": 0.5330149315409964,
   "annVol": 0.1525245441318232
  },
  {
   "symbol": "RTX",
   "name": "RTX Corporation",
   "marketCap": 300509623780,
   "score": 1.1404819075316022,
   "annReturn": 0.28369800343690615,
   "annVol": 0.2487527435230664
  },
  {
   "symbol": "ARM",
   "name": "Arm Holdings plc American Depositary Shares",
   "marketCap": 298441520121,
   "score": 0.8042826900339248,
   "annReturn": 0.5772020647095296,
   "annVol": 0.7176606830680182
  },
  {
   "symbol": "PM",
   "name": "Philip Morris International Inc.",
   "marketCap": 296743757900,
   "score": 0.2887635263535555,
   "annReturn": 0.08368396872200701,
   "annVol": 0.28980103470389906
  },
  {
   "symbol": "BABA",
   "name": "Alibaba Group Holding Limited",
   "marketCap": 296588955758,
   "score": 0.030789266671642845,
   "annReturn": 0.013539195678827273,
   "annVol": 0.4397375170775658
  }
 ]
};
